Update reusable-main.yml

diff --git a/.github/workflows/reusable-main.yml b/.github/workflows/reusable-main.yml
--- a/.github/workflows/reusable-main.yml
+++ b/.github/workflows/reusable-main.yml
@@ -1,4 +1,4 @@
-name: My reusable
+name: Verify and validate version from version file
 
 on:
   workflow_call:
@@ -22,8 +22,8 @@ jobs:
   verify_version:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout main code
-      uses: actions/checkout@v2
+    - name: Checkout version from main-branch code
+      uses: actions/checkout@v3
       with:
         ref: ${{ inputs.main-branch }}
     - name: Get latest version
@@ -31,17 +31,26 @@ jobs:
       run: |
         latest_version=$(cat ${{ inputs.file-name }} | tr -d '[:space:]')
         echo "::set-output name=latest_version::$latest_version"
-    - name: Checkout PR code
-      uses: actions/checkout@v2
+    - name: Checkout version from PR code
+      uses: actions/checkout@v3
     - name: Get current version
       id: get_current_version
       run: |
         current_version=$(cat ${{ inputs.file-name }} | tr -d '[:space:]')
         echo "::set-output name=current_version::$current_version"
-    - name: Compare versions
+    - name: Validate current version
+      run: |
+        current_version=${{ steps.get_current_version.outputs.current_version }}
+        
+        if ! [[ $current_version =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+(\.[0-9]+)*)?(\+[0-9]+(\.[0-9]+)*)?$ ]]; then
+          echo "Error: Value is not a valid semver."
+          exit 1
+        fi
+    - name: Verify and Compare versions
       run: |
         current_version=${{ steps.get_current_version.outputs.current_version }}
         latest_version=${{ steps.get_latest_version.outputs.latest_version }}
+        
         if [ $(echo -e "${current_version}\n${latest_version}"|sort -V|head -1) != "${current_version}" ]; then
           echo "Current version ($current_version) is greater than the latest version ($latest_version)"
         else
